//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regist
    {
        public int regist_id { get; set; }
        public Nullable<int> regist_name { get; set; }
        public Nullable<int> regist_book { get; set; }
        public Nullable<System.DateTime> regist_givendate { get; set; }
        public Nullable<System.DateTime> regist_returndate { get; set; }
        public Nullable<bool> regist_state { get; set; }
    
        public virtual Resources Resources { get; set; }
        public virtual Students Students { get; set; }
    }
}
