//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resources
    {
        public int resources_id { get; set; }
        public string resources_name { get; set; }
        public string resources_publisher { get; set; }
        public string resources_author { get; set; }
        public Nullable<System.DateTime> resources_date { get; set; }
        public Nullable<int> resources_page { get; set; }
    }
}
