//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int personal_id { get; set; }
        public string persona_name { get; set; }
        public string personal_surname { get; set; }
        public string personal_tc { get; set; }
        public string personal_tel { get; set; }
        public string personal_mail { get; set; }
        public string personal_username { get; set; }
        public string personal_password { get; set; }
    }
}
